# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "MinimalPortfolio"
description = ""
homepage = "http://example.com/"
license = "MIT"
licenselink = "https://github.com/MikeSteiner/minimal-portfolio-hugo-theme/master/LICENSE"
tags = []
features = []
min_version = "0.67.1"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""


