baseURL = 'https://cook-for-you.netlify.app'
languageCode = 'en-us'
title = 'Cook for you'

theme = "minimal-portfolio"

[taxonomies]
  tag = "tags"
  category = "categories"

# Logo
[params.logo]
    src = "bulgarian-kettlebells-logo.png"
    alt = "Bulgarian Kettlebells website"
    favicon = "/uploads/favicon.png"
    appleTouchIcon = "/uploads/apple-touch-icon.png"

# Navigation
sectionPagesMenu = "main"
[menu]
[[menu.main]]
    identifier = 'home'
    name = 'home'
    url = '/'
    weight = 10
[[menu.main]]
    identifier = 'about'
    name = 'about'
    url = '/about/'
    weight = 100
[[menu.main]]
    identifier = "salats"
    name = "Салати"
    weight = 20
    url = "/salats/"
[[menu.main]]
    identifier = "desserts"
    name = "Десерти"
    weight = 30
    url = "/desserts/"
    hasChildren = false
[[menu.main]]
    identifier = "soups"
    name = "Супи"
    weight = 40
    url = "/soups/"
    hasChildren = false
[[menu.main]]
    identifier = "ferments"
    name = "Туршии"
    weight = 50
    url = "/туршии/"
    hasChildren = false

# Mounts
[[module.mounts]]
    source = "images"
    target = "content/uploads"
[[module.mounts]]
    source = "assets"
    target = "assets"
[[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"
[[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"
[[module.mounts]]
    source = "node_modules/bootstrap-icons/font/fonts"
    target = "static/fonts"
[[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/vendor/js/bootstrap.bundle.min.js"
