baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Cook for you'

theme = "cookbook"

# Navigation
[[menu.main]]
    name = "home"
    label = "Начало"
    weight = 10
    url = "/index.html"
    hasChildren = false
[[menu.main]]
    name = "recipes"
    label = "Рецепти"
    weight = 20
    url = "/#page"
    hasChildren = false
[[menu.main]]
    name = "about"
    label = "За блога"
    weight = 30
    url = "/#elements"
    hasChildren = false

# Module
[module]
  [module.hugoVersion]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/webfonts"
    target = "static/webfonts"

  [[module.mounts]]
    source = "node_modules/jquery/dist/jquery.min.js"
    target = "assets/vendor/js/jquery.min.js"

  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/vendor/js/bootstrap.bundle.min.js"

  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/scss/bootstrap"

  [[module.mounts]]
    source = "node_modules/bootstrap-icons/font/fonts"
    target = "static/fonts"

  [[module.mounts]]
    source = "node_modules/boxicons/css"
    target = "assets/vendor/boxicons"

  [[module.mounts]]
    source = "node_modules/boxicons/fonts"
    target = "static/fonts"
